using System.IO;
using System.Text.Json;
using System.Windows.Controls;
using Microsoft.Web.WebView2.Core;
using TaskTool.Services;
using TaskTool.ViewModels;

namespace TaskTool.Views;
public partial class WebShortcutView : UserControl
{
    private CancellationTokenSource? _login;
    public WebShortcutView(){InitializeComponent();DataContextChanged+=(_,_)=>_ = NavigateAsync();}
    private async Task NavigateAsync(){if(DataContext is not WebShortcutViewModel vm||!Uri.TryCreate(vm.Url,UriKind.Absolute,out var uri)||(uri.Scheme!=Uri.UriSchemeHttp&&uri.Scheme!=Uri.UriSchemeHttps))return;try{var path=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Plenaro","WebView2","Shortcuts",vm.ShortcutId);var env=await CoreWebView2Environment.CreateAsync(null,path);await Browser.EnsureCoreWebView2Async(env);Browser.CoreWebView2.NavigationStarting-=Starting;Browser.CoreWebView2.NavigationStarting+=Starting;Browser.CoreWebView2.NavigationCompleted-=Completed;Browser.CoreWebView2.NavigationCompleted+=Completed;Browser.CoreWebView2.Navigate(uri.ToString());}catch(Exception ex){BrowserStatus.Text=$"Webseite konnte nicht geöffnet werden: {ex.Message}";}}
    private void Starting(object? s,CoreWebView2NavigationStartingEventArgs e){_login?.Cancel();if(!Uri.TryCreate(e.Uri,UriKind.Absolute,out var u)||(u.Scheme!=Uri.UriSchemeHttp&&u.Scheme!=Uri.UriSchemeHttps)){e.Cancel=true;BrowserStatus.Text="Navigation blockiert.";}}
    private void Completed(object? s,CoreWebView2NavigationCompletedEventArgs e){if(DataContext is not WebShortcutViewModel vm||!e.IsSuccess)return;if(Uri.TryCreate(Browser.Source?.ToString(),UriKind.Absolute,out var current))ServiceLocator.Logger.Info($"[WebShortcut] shortcutId={vm.ShortcutId} host={current.Host} navigation=success");if(!vm.Shortcut.AutoLogin||!Trusted(vm,current))return;var password=ServiceLocator.Settings.GetWebShortcutPassword(vm.Shortcut);if(password.Length==0||vm.Shortcut.Username.Length==0)return;_login=new();_=LoginAsync(vm,password,current!.Host,_login.Token);}
    private static bool Trusted(WebShortcutViewModel vm,Uri? current)=>current!=null&&Uri.TryCreate(vm.Url,UriKind.Absolute,out var configured)&&current.Scheme==Uri.UriSchemeHttps&&configured.Scheme==Uri.UriSchemeHttps&&current.Host.Equals(configured.Host,StringComparison.OrdinalIgnoreCase)&&current.Port==configured.Port;
    private async Task LoginAsync(WebShortcutViewModel vm,string password,string host,CancellationToken token){var schedule=new[]{0,300,800,1500};var prior=0;foreach(var at in schedule){try{if(at>prior)await Task.Delay(at-prior,token);prior=at;var result=await FillAsync(vm.Shortcut.Username,password);ServiceLocator.Logger.Info($"[WebShortcutLogin] shortcutId={vm.ShortcutId} host={host} loginPageDetected={result.Detected.ToString().ToLowerInvariant()} usernameFieldFound={result.User.ToString().ToLowerInvariant()} passwordFieldFound={result.Password.ToString().ToLowerInvariant()} submitted={result.Submitted.ToString().ToLowerInvariant()}");if(result.Detected)return;}catch(OperationCanceledException){return;}catch(Exception ex){ServiceLocator.Logger.Warning($"[WebShortcutLogin] shortcutId={vm.ShortcutId} host={host} errorType={ex.GetType().Name}");return;}}}
    private async Task<LoginResult> FillAsync(string username,string password){var u=JsonSerializer.Serialize(username);var p=JsonSerializer.Serialize(password);var script=$$"""(()=>{const q=s=>s.map(x=>document.querySelector(x)).find(Boolean)||null;const u=q(['input[autocomplete="username"]','input[type="email"]','input[name="username"]','input[name="user"]','input[name="User"]','input[name="login"]','input[id*="user" i]','input[id*="login" i]']);const p=q(['input[type="password"]','input[name="password"]','input[name="Password"]','input[id*="password" i]']);const f=p?.closest('form');const b=f&&['button[type="submit"]','input[type="submit"]','button[name*="login" i]','button[id*="login" i]'].map(x=>f.querySelector(x)).find(Boolean);const r={detected:!!(u&&p),user:!!u,password:!!p,submitted:false};if(!u||!p)return r;const set=(e,v)=>{const s=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;s?s.call(e,v):e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));};set(u,{{u}});set(p,{{p}});if(b){b.click();r.submitted=true;}else if(f?.requestSubmit){f.requestSubmit();r.submitted=true;}return r;})()""";using var d=JsonDocument.Parse(await Browser.CoreWebView2.ExecuteScriptAsync(script));var r=d.RootElement;return new(r.GetProperty("detected").GetBoolean(),r.GetProperty("user").GetBoolean(),r.GetProperty("password").GetBoolean(),r.GetProperty("submitted").GetBoolean());}
    private sealed record LoginResult(bool Detected,bool User,bool Password,bool Submitted);
}
